use("tobak_express");

db.products.insertMany([
  {
    name: "General Original Portion",
    brand: "General",
    category: "portion",
    nicotineStrength: "normal",
    nicotineMg: 8,
    weightGrams: 24,
    flavors: ["tobacco", "pepper"],
    price: 45.0,
    inStock: true,
  },
  {
    name: "Ettan Original Portion",
    brand: "Ettan",
    category: "portion",
    nicotineStrength: "normal",
    nicotineMg: 8.5,
    weightGrams: 24,
    flavors: ["tobacco"],
    price: 42.0,
    inStock: true,
  },
  {
    name: "Göteborgs Rape Original Portion",
    brand: "Göteborgs Rape",
    category: "portion",
    nicotineStrength: "normal",
    nicotineMg: 8,
    weightGrams: 24,
    flavors: ["lavender", "citrus"],
    price: 44.0,
    inStock: true,
  },
  {
    name: "LD Salmiak Vit Portion",
    brand: "LD",
    category: "portion",
    nicotineStrength: "normal",
    nicotineMg: 9,
    weightGrams: 24,
    flavors: ["liquorice"],
    price: 32.0,
    inStock: true,
  },
  {
    name: "Ettan Lös",
    brand: "Ettan",
    category: "loose",
    nicotineStrength: "normal",
    nicotineMg: 8.5,
    weightGrams: 42,
    flavors: ["tobacco", "smoky"],
    price: 39.0,
    inStock: true,
  },
  {
    name: "General Lös",
    brand: "General",
    category: "loose",
    nicotineStrength: "normal",
    nicotineMg: 8,
    weightGrams: 42,
    flavors: ["tobacco", "bergamot"],
    price: 40.0,
    inStock: false,
  },
]);

// Customers collection
db.customers.insertMany([
  {
    firstName: "Olof",
    lastName: "Palme",
    email: "olof.palme@gmail.se",
    phone: "+46701234567",
    country: "SE",
    address: {
      street: "Olof Palmes gata 12",
      city: "Stockholm",
      postalCode: "11122",
    },
    createdAt: new Date("2025-03-10"),
  },
  {
    firstName: "Pippi",
    lastName: "Longström",
    email: "pippi.longstrom@gmail.se",
    phone: "+46709876543",
    country: "SE",
    address: {
      street: "Huvikumpu 5",
      city: "Gothenburg",
      postalCode: "41101",
    },
    createdAt: new Date("2024-05-22"),
  },
  {
    firstName: "Bosse",
    lastName: "Andersson",
    email: "bosse.andersson@gmail.se",
    phone: "+46723456789",
    country: "SE",
    address: {
      street: "Vasagatan 8",
      city: "Malmö",
      postalCode: "21120",
    },
    createdAt: new Date("2025-07-01"),
  },
  {
    firstName: "Stig",
    lastName: "Engström",
    email: "stig.engstrom@gmail.se",
    phone: "+46731122334",
    country: "SE",
    address: {
      street: "Drottninggatan 3",
      city: "Stockholm",
      postalCode: "11122",
    },
    createdAt: new Date("2024-08-15"),
  },
  {
    firstName: "Nasse",
    lastName: "Nuutinen",
    email: "nasse.nuutinen@test.fi",
    phone: "+358401234567",
    country: "FI",
    address: {
      street: "Kaivokatu 10",
      city: "Helsinki",
      postalCode: "00100",
    },
    createdAt: new Date("2024-09-03"),
  },
  {
    firstName: "Johan",
    lastName: "Kläbo",
    email: "johan.klabo@test.no",
    phone: "+4791234567",
    country: "NO",
    address: {
      street: "Karl gate 7",
      city: "Oslo",
      postalCode: "1234",
    },
    createdAt: new Date("2026-01-18"),
  },
]);